# Generated by Django 5.2.8 on 2025-11-26 14:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.CreateModel(
            name='UserCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('canonical', models.CharField(max_length=255, unique=True, verbose_name='Canonical')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('creator', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalogues', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'User Catalogue',
                'verbose_name_plural': 'User Catalogues',
                'db_table': 'user_catalogues',
            },
        ),
        migrations.CreateModel(
            name='UserCatalogueUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_catalogue', models.ForeignKey(db_column='user_catalogue_id', on_delete=django.db.models.deletion.CASCADE, to='users.usercatalogue')),
            ],
            options={
                'verbose_name': 'User Catalogue Assignment',
                'verbose_name_plural': 'User Catalogue Assignments',
                'db_table': 'user_catalogue_user',
            },
        ),
        migrations.AddField(
            model_name='usercatalogue',
            name='users',
            field=models.ManyToManyField(related_name='catalogues', through='users.UserCatalogueUser', to=settings.AUTH_USER_MODEL, verbose_name='Users in this catalogue'),
        ),
    ]
