# Generated by Django 5.2.8 on 2025-12-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_created_at_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercatalogue',
            name='publish',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], default=2),
        ),
        migrations.AddConstraint(
            model_name='usercatalogue',
            constraint=models.CheckConstraint(condition=models.Q(('publish__in', [1, 2])), name='users_usercatalogue_publish_valid'),
        ),
    ]
