# Generated by Django 5.2.8 on 2026-01-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_deleted_at_usercatalogueuser_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
    ]
