# Generated by Django 5.2.8 on 2026-01-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_remove_user_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercatalogue',
            name='users',
        ),
        migrations.AlterModelTable(
            name='usercatalogue',
            table=None,
        ),
        migrations.DeleteModel(
            name='UserCatalogueUser',
        ),
    ]
