# Generated by Django 5.2.8 on 2026-02-12 15:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_usercatalogue_users_alter_usercatalogue_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=255)),
                ('canonical', models.CharField(max_length=255, unique=True, verbose_name='Canonical')),
                ('description', models.TextField(blank=True, default='')),
                ('publish', models.IntegerField(choices=[(1, '1'), (2, '2')], default=2)),
                ('creator', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'constraints': [models.CheckConstraint(condition=models.Q(('publish__in', [1, 2])), name='users_permission_publish_valid')],
            },
        ),
    ]
