# Generated by Django 5.2.8 on 2026-02-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercatalogue',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='user_catalogues', to='users.permission'),
        ),
    ]
